In [10]:
import cv2
import numpy as np

In [11]:
faceCascade=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [12]:
img=cv2.imread("faces.jpg")
imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [13]:
faces=faceCascade.detectMultiScale(imgGray,1.1,4)

In [14]:
print(faces)

[[ 97 134  34  34]
 [430 130  36  36]
 [136  42  30  30]
 [282  42  48  48]
 [214  63  32  32]
 [390  78  32  32]]


In [15]:
for face in faces:
    cv2.rectangle(img,(face[0],face[1]),(face[0]+face[2],face[1]+face[3]),(0,0,255),2)

In [16]:
cv2.imshow("img",img)
cv2.waitKey(0)

-1